replicaCount: 1

image:
  repository: 986154984217.dkr.ecr.ap-northeast-1.amazonaws.com/container-nodejs-api-8000
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-secret

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8000
  nodePort: ""

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  create: true
  name: express-app
  imagePullSecrets:
    - name: ecr-secret

# Ingress設定を追加
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Autoscaling設定を追加
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  scaleDownDelaySeconds: 300
